M48
; DRILL file {KiCad (6.0.1)} date Thu Mar  2 15:38:06 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-02T15:38:06+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.413Y-5.9213
T2
X3.0551Y-2.7559
X3.0551Y-6.1102
X6.275Y-2.7559
X6.2756Y-6.1102
T0
M30
